---
name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

        with:
          driver: docker-container
          driver-opts: network=host

      - uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_PASS }}

      - id: prepare
        run: |
          echo "tag=$(cat ./version)"  >> $GITHUB_ENV;

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tags: registry.cn-hangzhou.aliyuncs.com/${{ secrets.NS }}/gitlab:${{ env.tag }}
